INSERT INTO department (dept_name)
VALUES
  ('President'),
  ('Officer'),
  ('Manager'),
  ('Associate'),
  ('Junior');

INSERT INTO job (title, salary, dept_id)
VALUES
  ('President', '750000.00', '1'),
  ('Chief Executive Officer', '500000.00', '2'),
  ('Chief Operating Officer', '500000.00', '2'),
  ('Chief Finance Officer', '500000.00', '2'),
  ('Chief Marketing Officer', '500000.00', '2'),
  ('Sales Manager', '250000.00', '3'),
  ('Production Manager', '250000.00', '3'),
  ('Quality Manager', '250000.00', '3'),
  ('Shipping Manager', '250000.00', '3'),
  ('IT Manager', '250000.00', '3'),
  ('Sales Associate', '100000.00', '4'),
  ('Production Associate', '100000.00', '4'),
  ('Quality Technician', '100000.00', '4'),
  ('Shipping Associate', '100000.00', '4'),
  ('Software Engineer', '100000.00', '4'),
  ('Mechanical Engineer', '100000.00', '4'),
  ('HR Representative', '100000.00', '4'),
  ('Junior Web Developer', '75000.00', '5'),
  ('Junior Salesman', '75000.00', '5'),
  ('Executive Assistant', '75000.00', '5'),
  ('HR Assistant', '75000.00', '5');

INSERT INTO employee (first_name, last_name, job_id, manager_id)
VALUES
  ('Gandalf', 'Stormcrow', '1', NULL),
  ('Aragorn', 'Arathornson', '2', '1'),
  ('Legolas', 'Greenleaf', '2', '1'),
  ('Gimli', 'Gloinson', '2', '1'),
  ('Boromir', 'Denethorson', '2', '1'),
  ('Frodo', 'Baggins', '3', '1'),
  ('Samwise', 'Gamgee', '2', '1'),
  ('Meriadoc', 'Brandybuck', '2', '1'),
  ('Peregrin', 'Took', '2', '1'),
  ('Bilbo', 'Baggins', '2', '1'),
  ('Theoden', 'Eorl', '2', '1'),
  ('Eomer', 'Eadig', '2', '1'),
  ('Eowyn', 'Eadig', '2', '1'),
  ('Arwen', 'Evenstar', '2', '1'),
  ('Tom', 'Bombadill', '2', '1'),
  ('Smeagol', 'Gollum', '2', '1'),
  ('Saruman', 'White', '2', '1'),
  ('Radagast', 'Brown', '2', '1'),
  ('Thorin', 'Oakenshield', '2', '1'),
  ('Balin', 'Fundinson', '2', '1'),
  ('Albus', 'Dumbledore', '2', '1'),
  ('Minerva', 'McGonagall', '2', '1'),
  ('Severus', 'Snape', '2', '1'),
  ('Remus', 'Lupin', '2', '1'),
  ('Alastor', 'Moody', '2', '1'),
  ('Sybil', 'Trelawney', '2', '1'),
  ('Filius', 'Flitwick', '2', '1'),
  ('Gilderoy', 'Lockhart', '2', '1'),
  ('Pomona', 'Sprout', '2', '1'),
  ('Harry', 'Potter', '2', '1'),
  ('Ron', 'Weasley', '2', '1'),
  ('Hermione', 'Granger', '2', '1'),
  ('Neville', 'Longbottom', '2', '1'),
  ('Draco', 'Malfoy', '2', '1'),
  ('Dudley', 'Dursley', '2', '1'),
  ('Rubeus', 'Hagrid', '2', '1'),
  ('Luna', 'Lovegood', '2', '1'),
  ('Ginny', 'Weasley', '2', '1'),
  ('George', 'Weasley', '2', '1'),
  ('Fred', 'Weasley', '2', '1'),
  ('Bill', 'Weasley', '2', '1'),
  ('Percy', 'Weasley', '2', '1'),
  ('Sirius', 'Black', '2', '1'),
  ('John', 'Snow', '2', '1'),
  ('Eddard', 'Stark', '2', '1'),
  ('Robb', 'Stark', '2', '1'),
  ('Catelyn', 'Stark', '2', '1'),
  ('Sansa', 'Stark', '2', '1'),
  ('Arya', 'Stark', '2', '1'),
  ('Bran', 'Stark', '2', '1'),
  ('Theon', 'Greyjoy', '2', '1'),
  ('Tyrion', 'Lannister', '2', '1'),
  ('Jamie', 'Lannister', '2', '1'),
  ('Cersei', 'Lannister', '2', '1'),
  ('Robert', 'Baratheon', '2', '1'),
  ('Joffrey', 'Baratheon', '2', '1'),
  ('Renly', 'Baratheon', '2', '1'),
  ('Stannis', 'Baratheon', '2', '1'),
  ('Tommen', 'Baratheon', '2', '1'),
  ('Margeary', 'Tyrell', '2', '1'),
  ('Daenerys', 'Targaryen', '2', '1'),
  ('Tywin', 'Lannister', '2', '1'),
  ('Samwell', 'Tarly', '2', '1'),
  ('Sandor', 'Clegane', '2', '1'),
  ('Brienne', 'Tarth', '2', '1'),
  ('Petyr', 'Baelish', '2', '1'),
  ('Jorah', 'Mormont', '2', '1'),